version: "3.2"

services:
    guppy:
        build: .
        restart: always
        ports:
            - 3000:3000
        environment:
            - SERVER_ADDRESS=0.0.0.0
            - SERVER_PORT=3000
            - SERVER_TIMEZONE=Asia/Jakarta
            - SWAGGER_SERVER_ADDRESS=http://0.0.0.0
            - OS_URLS=localhost:32771,localhost:32772,localhost:32773
            - OS_DIAL_TIMEOUT=5
            - PASSPHRASE=z4yH36a6zerhfE5427ZV
        command: air